repos:

- repo: local
  hooks:
    - id: black
      name: Black
      entry: bash -c 'poetry run black .'
      require_serial: true
      language: system
      types: [python]
    - id: isort
      name: Isort
      entry: bash -c 'poetry run isort .'
      require_serial: true
      language: system
      types: [python]
    - id: flake8
      name: Flake8
      entry: bash -c 'poetry run flake8 .'
      require_serial: true
      language: system
      types: [python]
